### ISSUE TITLE
The game does not start, installed everything correctly

### ISSUE THREAD

**Issue by Dima121321** [Odex64/SFR#8]
The game throws an error when starting:
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at MonoMod.Core.Platforms.Architectures.x86Shared.TryRel32Detour(IntPtr from, IntPtr to, Int32 sizeHint, NativeDetourInfo& info)
   at MonoMod.Core.Platforms.Architectures.x86Arch.ComputeDetourInfo(IntPtr from, IntPtr to, Int32 maxSizeHint)
   at MonoMod.Core.Platforms.PlatformTriple.CreateSimpleDetour(IntPtr from, IntPtr to, Int32 detourMaxSize, IntPtr fromRw)
   at MonoMod.Core.Platforms.PlatformTripleDetourFactory.Detour.CreateDetour()
   at MonoMod.Core.Platforms.PlatformTripleDetourFactory.DetourBase.Apply()
   at MonoMod.Core.Platforms.PlatformTripleDetourFactory.CreateDetour(CreateDetourRequest request)
   at MonoMod.Core.DetourFactory.CreateDetour(IDetourFactory factory, MethodBase source, MethodBase target, Boolean applyByDefault)
   at HarmonyLib.PatchTools.DetourMethod(MethodBase method, MethodBase replacement)
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchClassProcessor.ProcessPatchJob(Job job)
   at HarmonyLib.PatchClassProcessor.PatchWithAttributes(MethodBase& lastOriginal)
   at HarmonyLib.PatchClassProcessor.Patch()
   at HarmonyLib.Harmony.<PatchAll>b__10_0(Type type)
   at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at HarmonyLib.Harmony.PatchAll(Assembly assembly)
   at HarmonyLib.Harmony.PatchAll()
   at SFR.Program.Main(String[] args)

**Comment by Odex64** [comment]
Weird things happen when you do a lot of modifications at runtime 😊
